### ISSUE TITLE
Xcode 10 Swift 4.2 Support

### ISSUE THREAD

**Issue by npocmo** [googleapis/auth-library-swift#10]
I'm having problems adding AuthLibrary via Pods. I assume its due to Xcode 10 and Swift 4.2. 

Is any support of Xcode 10 and Swift 4.2 planned?

**Comment by timburks** [comment]
Confirming, I get these errors when I build with Swift 4.2.1:
```
/Users/timburks/Desktop/auth-library-swift/.build/checkouts/http-8245225851887671563/Sources/HTTP/PoCSocket/PoCSocket.swift:81:20: warning: 'initialize(to:count:)' is deprecated: renamed to 'initialize(repeating:count:)'
        readBuffer.initialize(to: 0x0, count: maxLength)
                   ^
/Users/timburks/Desktop/auth-library-swift/.build/checkouts/http-8245225851887671563/Sources/HTTP/PoCSocket/PoCSocket.swift:81:20: note: use 'initialize(repeating:count:)' instead
        readBuffer.initialize(to: 0x0, count: maxLength)
                   ^~~~~~~~~~ ~~
                   initialize repeating
/Users/timburks/Desktop/auth-library-swift/.build/checkouts/http-8245225851887671563/Sources/HTTP/PoCSocket/PoCSocket.swift:230:51: error: overlapping accesses to 'addr_in', but modification requires exclusive access; consider copying to a local variable
        listeningPort = try withUnsafePointer(to: &addr_in) { pointer in
                                                  ^~~~~~~~
/Users/timburks/Desktop/auth-library-swift/.build/checkouts/http-8245225851887671563/Sources/HTTP/PoCSocket/PoCSocket.swift:238:81: note: conflicting access is here
                return Int32(Int(OSHostByteOrder()) != OSLittleEndian ? addr_in.sin_port.littleEndian : addr_in.sin_port.bigEndian)
                                                                        ~~~~~~~~^~~~~~~~
error: terminated(1): /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-build-tool -f /Users/timburks/Desktop/auth-library-swift/.build/release.yaml main output:
    

make: *** [all] Error 1
```

**Comment by timburks** [comment]
Please try [version 0.4.0](https://github.com/googleapis/auth-library-swift/releases/tag/0.4.0).
